variables:
  GIT_SSL_NO_VERIFY: "1"
.check: &check
    - VERSION_FROM_PACKAGE=$(node -p -e "require('./package.json').version")
    - echo $VERSION
    - echo $VERSION_FROM_PACKAGE
    - if [ $VERSION == $VERSION_FROM_PACKAGE ]; then
        echo "Version match";
      else
        echo "The version doesnt match the package.json and the TAG" &&
        exit -1;
      fi
.addCredential: &addCredential
    - rm -f ~/.npmrc
    - echo -e "_auth = $XRHTSERVICE_PASS_B64\nemail = $XRHTSERVICE_EMAIL\nalways-auth = true" >>  ~/.npmrc
.package: &package
    - npm config set strict-ssl false
    - npm --userconfig ~/.npmrc publish --registry $NPM_DOMAIN_NAME
stages:
  - check
  - addCredential
  - package

check:
  stage: check
  tags:
    - HaT_SDK
  except:
    - branches
  before_script:
    # additional variables
    - VERSION=$(echo $CI_COMMIT_REF_NAME)
  script:
    *check
addCredential:
  stage: addCredential
  except:
    - branches
  tags:
    - HaT_SDK
  script:
    *addCredential

package:
  stage: package
  except:
    - branches
  environment:
    name: preview
  tags:
    - HaT_SDK
  script:
    *package
